# SonarCloud analysis
name: SonarCloud analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Analyze with SonarCloud
        # use a released tag for readability, or keep a pinned SHA if you prefer strict pinning
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=kumartrinetra_Basic-one-to-one-chatting-app-using-flutter-and-firebase
            -Dsonar.organization=kumartrinetra
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=lib
          projectBaseDir: .
